### ISSUE TITLE
Why can’t I see liquidity locally, but it’s ok at https://pcs.nhancv.com/

### ISSUE THREAD

**Issue by xiemiaogit** [nhancv/pancake-swap-testnet#1]
hello nhancv !
Can you help me see the problem, thanks !

at locally:
![image](https://user-images.githubusercontent.com/17972945/126158793-d7e11ce5-16c6-4811-8e6f-9558e8dbb4a5.png)

at https://pcs.nhancv.com/
![image](https://user-images.githubusercontent.com/17972945/126158935-fd4f8380-142e-4926-adb5-2c790c8eea46.png)

**Comment by nhancv** [comment]
I see. Because when you clone and install it the first time, yarn/npm will download @pancakeswap-libs/sdk originally, it did not use my config (router/hash/factory/wbnb address) -> Check https://github.com/nhancv/pancake-swap-testnet#setup-frontend

Another way: just copy this `pancake-swap-testnet/build/@pancakeswap-libs_sdk_dist` folder replace to `pancake-swap-testnet/node_modules/@pancakeswap-libs/sdk/dist`

**Comment by xiemiaogit** [comment]
That's it, I solved the problem, thanks!
